=== Saldiga01/ledwall-management-system/src/main/resources/static/xml/palinsesto.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">

    <xs:simpleType name="stringtype">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="inttype">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>
    
    <xs:element name="palinsesto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="advertisement" type="advertisementType" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="idPalinsesto" type="inttype" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="advertisementType">
        <xs:sequence>
            <xs:element name="file" type="stringtype"/>
            <xs:element name="duration" type="inttype"/>
        </xs:sequence>
        <xs:attribute name="idCartellone" type="inttype" use="required"/>
    </xs:complexType>

</xs:schema>

=== Saldiga01/ledwall-management-system/src/main/resources/static/xml/palinsesto3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE ledWall SYSTEM "ledWall.dtd">-->

<palinsesto idPalinsesto="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <advertisement idCartellone="102">
        <file>/html/dolce&amp;gabbana.html</file>
        <duration>7</duration>
    </advertisement>
    <advertisement idCartellone="104">
        <file>/html/McDonalds.html</file>
        <duration>35</duration>
    </advertisement>
    <advertisement idCartellone="109">
        <file>/html/onePlus.html</file>
        <duration>12</duration>
    </advertisement>
    <advertisement idCartellone="105">
        <file>/html/radio105.html</file>
        <duration>8</duration>
    </advertisement>
    <advertisement idCartellone="103">
        <file>/html/juve_abbonamenti.html</file>
        <duration>7</duration>
    </advertisement>
</palinsesto>

=== Saldiga01/ledwall-management-system/src/main/resources/static/xml/palinsesto2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE ledWall SYSTEM "ledWall.dtd">-->

<palinsesto idPalinsesto="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <advertisement idCartellone="106">
        <file>/html/michelin.html</file>
        <duration>35</duration>
    </advertisement>
    <advertisement idCartellone="107">
        <file>/html/sector.html</file>
        <duration>11</duration>
    </advertisement>
    <advertisement idCartellone="108">
        <file>/html/relaxdasogno.html</file>
        <duration>37</duration>
    </advertisement>
    <advertisement idCartellone="109">
        <file>/html/onePlus.html</file>
        <duration>9</duration>
    </advertisement>
    <advertisement idCartellone="110">
        <file>/html/sky_wifi.html</file>
        <duration>7</duration>
    </advertisement>
</palinsesto>

=== Saldiga01/ledwall-management-system/src/main/resources/static/xml/palinsesto4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE ledWall SYSTEM "ledWall.dtd">-->

<palinsesto idPalinsesto="4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <advertisement idCartellone="103">
        <file>/html/juve_abbonamenti.html</file>
        <duration>6</duration>
    </advertisement>
    <advertisement idCartellone="101">
        <file>/html/casa-di-carta.html</file>
        <duration>9</duration>
    </advertisement>
    <advertisement idCartellone="107">
        <file>/html/sector.html</file>
        <duration>11</duration>
    </advertisement>
    <advertisement idCartellone="106">
        <file>/html/michelin.html</file>
        <duration>35</duration>
    </advertisement>
    <advertisement idCartellone="105">
        <file>/html/radio105.html</file>
        <duration>10</duration>
    </advertisement>
</palinsesto>
